# -*- coding: utf-8 -*-
"""talent-match-intelligence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TOU3-Y_Br2iXeJmRZn9XiPia-RBozDry
"""

#@title Install & import libraries
!pip install pandas numpy matplotlib seaborn plotly openpyxl

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

pd.set_option("display.max_columns", 200)

#@title Upload Excel file
from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
print("Uploaded:", file_name)

#@title Load all sheets
xls = pd.ExcelFile(file_name)
sheets = xls.sheet_names
sheets

dfs = {sheet: pd.read_excel(xls, sheet) for sheet in sheets}
dfs.keys()

dfs["employees"].head()

"""

---

"""

#@title Identifikasi High Performers (Rating = 5)

df_perf = dfs["performance_yearly"]
df_emps = dfs["employees"]

# Filter karyawan dengan rating 5
df_hp = df_perf[df_perf["rating"] == 5]

print("Jumlah High Performers:", len(df_hp))
df_hp.head()

#@title Merge High Performer Dengan Data Employees (Profil Lengkap)

df_hp_detail = df_hp.merge(df_emps, on="employee_id", how="left")
df_hp_detail.head()

#@title Distribusi Rating Karyawan

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(7,4))
sns.countplot(data=df_perf, x="rating")
plt.title("Distribusi Rating Karyawan")
plt.show()

#@title Ambil Data Kompetensi Tahun Terbaru

df_comp = dfs["competencies_yearly"]

latest_year = df_comp["year"].max()
print("Tahun kompetensi terbaru:", latest_year)

df_comp_latest = df_comp[df_comp["year"] == latest_year]
df_comp_latest.head()

#@title Tambahkan Label High Performer Ke Data Kompetensi

df_comp_latest["is_hp"] = df_comp_latest["employee_id"].isin(df_hp["employee_id"])
df_comp_latest.head()

#@title Pivot Table Kompetensi (High vs Non-High Performer)

pivot_comp = df_comp_latest.pivot_table(
    index="pillar_code",
    columns="is_hp",
    values="score",
    aggfunc="mean"
)

pivot_comp.columns = ["Non-High Performer", "High Performer"]
pivot_comp

#@title Visualisasi Perbedaan Kompetensi (Barplot)

pivot_comp.plot(kind="bar", figsize=(12,6))
plt.title("Rata-rata Score Kompetensi (High vs Non-High Performer)")
plt.xticks(rotation=45)
plt.ylabel("Rata-rata Score")
plt.show()

"""----"""

#@title Analisis PAPI: High vs Non-High Performer

df_papi = dfs["papi_scores"]

# Tambah label high performer
df_papi["is_hp"] = df_papi["employee_id"].isin(df_hp["employee_id"])

# Pivot PAPI
pivot_papi = df_papi.pivot_table(
    index="scale_code",
    columns="is_hp",
    values="score",
    aggfunc="mean"
)

pivot_papi.columns = ["Non-High Performer", "High Performer"]
pivot_papi

#@title Visualisasi PAPI (High vs Non-High)

pivot_papi.plot(kind="bar", figsize=(16,6))
plt.title("PAPI Scores: High vs Non-High Performer")
plt.xticks(rotation=45)
plt.ylabel("Rata-rata Score")
plt.show()

"""

---

"""

#@title Cek Semua Kolom di profiles_psych
df_psy = dfs["profiles_psych"]
df_psy.columns

#@title Analisis Cognitive (IQ, GTQ, TIKI, Faxtor, Pauli)

df_psy = dfs["profiles_psych"]

# label high performer
df_psy["is_hp"] = df_psy["employee_id"].isin(df_hp["employee_id"])

# kolom cognitive (versi dataset ini)
cognitive_cols = ["iq", "gtq", "tiki", "faxtor", "pauli"]

df_cog = df_psy[["employee_id", "is_hp"] + cognitive_cols]

# hitung mean
pivot_cog = df_cog.groupby("is_hp")[cognitive_cols].mean().T
pivot_cog.columns = ["Non-High Performer", "High Performer"]

pivot_cog

#@title Visualisasi Cognitive (Barplot Per Variabel)

pivot_cog.plot(kind="bar", figsize=(10,6))
plt.title("Cognitive Scores: High vs Non-High Performer")
plt.xticks(rotation=0)
plt.ylabel("Rata-rata Score")
plt.show()

#@title Analisis MBTI (High vs Non-High Performer)

df_psy = dfs["profiles_psych"].copy()

# Bersihkan MBTI (uppercase, remove spaces)
df_psy["mbti_clean"] = df_psy["mbti"].str.upper().str.replace(" ", "")

# Label HP
df_psy["is_hp"] = df_psy["employee_id"].isin(df_hp["employee_id"])

# Pivot MBTI
pivot_mbti = df_psy.groupby(["mbti_clean", "is_hp"]).size().unstack(fill_value=0)

pivot_mbti.columns = ["Non-High Performer", "High Performer"]
pivot_mbti

#@title Analisis DISC (High vs Non-High Performer)

df_psy["disc_clean"] = df_psy["disc"].str.upper().str.strip()

pivot_disc = df_psy.groupby(["disc_clean", "is_hp"]).size().unstack(fill_value=0)
pivot_disc.columns = ["Non-High Performer", "High Performer"]

pivot_disc

#@title Analisis Strengths (CliftonStrengths): High vs Non-High Performer

df_strength = dfs["strengths"].copy()
df_strength["is_hp"] = df_strength["employee_id"].isin(df_hp["employee_id"])

# Count theme frequency
pivot_strength = df_strength.groupby(["theme", "is_hp"]).size().unstack(fill_value=0)
pivot_strength.columns = ["Non-High Performer", "High Performer"]

pivot_strength.sort_values("High Performer", ascending=False).head(20)

"""-----"""

#@title Save all sheets in the Excel file as CSV files

import pandas as pd
import os

excel_path = "/content/Study Case DA.xlsx"  # ganti sesuai path kamu

xls = pd.ExcelFile(excel_path)
sheets = xls.sheet_names

output_dir = "/content/csv_output/"
os.makedirs(output_dir, exist_ok=True)

for sheet in sheets:
    df = pd.read_excel(xls, sheet)
    filename = f"{sheet}.csv".replace(" ", "_")
    csv_path = os.path.join(output_dir, filename)
    df.to_csv(csv_path, index=False)
    print(f"Saved: {csv_path}")

print("\nAll sheets exported to CSV!")

#@title Download CSV files from Google Colab

from google.colab import files
import os

csv_folder = "/content/csv_output/"

for fname in os.listdir(csv_folder):
    if fname.endswith(".csv"):
        files.download(os.path.join(csv_folder, fname))

#@title 🔧 FIX ALL CSV — convert floats to integers for Supabase Upload

import pandas as pd
import os

base = "/content/csv_output/"

def fix_int_columns(filename, int_cols):
    path = os.path.join(base, filename)
    df = pd.read_csv(path)

    for col in int_cols:
        if col in df.columns:
            df[col] = df[col].fillna(0).astype(int)

    fixed_name = filename.replace(".csv", "_fixed.csv")
    df.to_csv(os.path.join(base, fixed_name), index=False)
    print(f"[OK] {fixed_name} created")

# 1. competencies_yearly
fix_int_columns(
    "competencies_yearly.csv",
    ["score", "year"]
)

# 2. papi_scores
fix_int_columns(
    "papi_scores.csv",
    ["score"]
)

# 3. performance_yearly
fix_int_columns(
    "performance_yearly.csv",
    ["year", "rating"]
)

# 4. profiles_psych
fix_int_columns(
    "profiles_psych.csv",
    ["iq", "gtq", "tiki", "faxtor", "pauli"]
)

print("\nAll FIXED CSV files generated successfully.")

#@title 📥 Download all *_fixed.csv files

from google.colab import files
import os

folder = "/content/csv_output/"
for f in os.listdir(folder):
    if f.endswith("_fixed.csv"):
        print("Downloading:", f)
        files.download(os.path.join(folder, f))